version: '2'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  mongodb:
    image: mongo:latest
    restart: always
    ports:
        - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_DATABASE}
    volumes:
        - mongo:/var/lib/mongo/data

volumes:
  redis:
  mongo:
